### ISSUE TITLE
ggplot geom_tile legend color scale is not save properly to ppt - corrupted 

### ISSUE THREAD

**Issue by nettam** [tanaylab/tgppt#2]
Example:
x <- LETTERS[1:20]
y <- paste0("var", seq(1,20))
data <- expand.grid(X=x, Y=y)
data$Z <- runif(400, 0, 5)
 
# Heatmap 
g <- ggplot(data, aes(X, Y, fill= Z)) + geom_tile()
tgppt::plot_gg_ppt(g, out_ppt='t.pptx')

**Comment by aviezerl** [comment]
Can you send a screenshot? I just tried running your example and got the following in the ppt: 

![image](https://user-images.githubusercontent.com/18175550/163360814-fad90034-af33-4c2c-aa8f-5581bb0d0cfc.png)

**Comment by aviezerl** [comment]
Or maybe you are not running the latest package version (from github)?
