### ISSUE TITLE
Unable to install tgppt in bioconductor 3.14

### ISSUE THREAD

**Issue by tanmayroy1979** [tanaylab/tgppt#3]
I am getting error while instaling the package

"
x86_64-conda-linux-gnu-c++ -std=gnu++11 -I"/home/tanmay/miniconda3/envs/Meth/lib/R/include" -DNDEBUG  -I'/home/tanmay/miniconda3/envs/Meth/lib/R/library/cpp11/include' -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/tanmay/miniconda3/envs/Meth/include -I/home/tanmay/miniconda3/envs/Meth/include -Wl,-rpath-link,/home/tanmay/miniconda3/envs/Meth/lib   -fpic  -fvisibility-inlines-hidden  -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/tanmay/miniconda3/envs/Meth/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base-split_1648745733215/work=/usr/local/src/conda/r-base-4.1.3 -fdebug-prefix-map=/home/tanmay/miniconda3/envs/Meth=/usr/local/src/conda-prefix  -c caches.cpp -o caches.o
In file included from caches.h:7,
                 from caches.cpp:1:
ft_cache.h:9:10: fatal error: ft2build.h: No such file or directory
    9 | #include <ft2build.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make: *** [/home/tanmay/miniconda3/envs/Meth/lib/R/etc/Makeconf:177: caches.o] Error 1
ERROR: compilation failed for package ‘systemfonts’
* removing ‘/home/tanmay/miniconda3/envs/Meth/lib/R/library/systemfonts’
ERROR: dependency ‘systemfonts’ is not available for package ‘gdtools’
* removing ‘/home/tanmay/miniconda3/envs/Meth/lib/R/library/gdtools’
ERROR: dependency ‘gdtools’ is not available for package ‘rvg’
* removing ‘/home/tanmay/miniconda3/envs/Meth/lib/R/library/rvg’

The downloaded source packages are in
	‘/tmp/RtmpTxrJDm/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Running `R CMD build`...
* checking for file ‘/tmp/RtmpTxrJDm/remotes73787b515c86/tanaylab-tgppt-416c12f/DESCRIPTION’ ... OK
* preparing ‘tgppt’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
Omitted ‘LazyData’ from DESCRIPTION
* building ‘tgppt_0.0.7.tar.gz’
ERROR: dependency ‘rvg’ is not available for package ‘tgppt’
* removing ‘/home/tanmay/miniconda3/envs/Meth/lib/R/library/tgppt’
Warning messages:
1: In i.p(...) :
  installation of package ‘systemfonts’ had non-zero exit status
2: In i.p(...) :
  installation of package ‘gdtools’ had non-zero exit status
3: In i.p(...) : installation of package ‘rvg’ had non-zero exit status
4: In i.p(...) :
  installation of package ‘/tmp/RtmpTxrJDm/file73784b8e6672/tgppt_0.0.7.tar.gz’ had non-zero exit status
> 
"

**Comment by aviezerl** [comment]
Seems like it is a problem with the systemfonts package, I suggest you post the issue there: 

https://github.com/r-lib/systemfonts/issues

Aviezer
